In [45]:
import pandas as pd
import numpy as np

In [46]:
from sklearn import datasets
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [47]:
dataset=datasets.load_diabetes()

In [48]:
df=np.array([1,0,1,0.01,0.001,0.0001,0])

In [49]:
model=Ridge()

In [50]:
grid=GridSearchCV(estimator=model,param_grid=dict(alpha=df))

In [51]:
import warnings
warnings.filterwarnings('ignore')
grid.fit(dataset.data,dataset.target)
print(grid)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='warn', n_jobs=None,
             param_grid={'alpha': array([1.e+00, 0.e+00, 1.e+00, 1.e-02, 1.e-03, 1.e-04, 0.e+00])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)


In [52]:
print(grid.best_score_)
print(grid.best_estimator_.alpha)

0.48879020446060145
0.001


RANDOM SEARCH PARAMETER TUNING

In [53]:
import numpy as np
from scipy.stats import uniform as sp_rand

In [54]:
from sklearn import datasets
from sklearn.linear_model import Ridge
from sklearn.model_selection import RandomizedSearchCV

In [55]:
datasets=datasets.load_diabetes()
param_grid={'alpha':sp_rand()}

In [56]:
models=Ridge()
rsearch=RandomizedSearchCV(estimator=model,param_distributions=param_grid,n_iter=100)

In [57]:
rsearch.fit(dataset.data,datasets.target)
print(rsearch)

RandomizedSearchCV(cv='warn', error_score='raise-deprecating',
                   estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                                   max_iter=None, normalize=False,
                                   random_state=None, solver='auto',
                                   tol=0.001),
                   iid='warn', n_iter=100, n_jobs=None,
                   param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002895F6552E8>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)


In [58]:
print(rsearch.best_score_)
print(rsearch.best_estimator_.alpha)

0.4891570767152947
0.06346044149343777


using another dataset

In [68]:
from sklearn import svm,datasets
from sklearn.model_selection import GridSearchCV

In [73]:
 >>> from sklearn.model_selection import GridSearchCV
>>> iris = datasets.load_iris()
>>> parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
>>> svc = svm.SVC()
>>> clf = GridSearchCV(svc, parameters)
>>> clf.fit(iris.data, iris.target)
GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')})
>>> sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_C',
 'param_kernel',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [27]:
# applying above information in the below dataset to predict that a person is  
#infected with hepatitis or not mainly use gridsearchcv 
import pandas as pd
import numpy as np

In [33]:
df=pd.read_csv("hepatitis.csv")
df.head()

2  30  2.1  1  2.2 2.3 2.4 2.5 1.1 2.6 2.7 2.8 2.9 2.10   1.2   85   18  \
0  2  50    1  1    2   1   2   2   1   2   2   2   2    2  0.90  135   42   
1  2  78    1  2    2   1   2   2   2   2   2   2   2    2  0.70   96   32   
2  2  31    1  ?    1   2   2   2   2   2   2   2   2    2  0.70   46   52   
3  2  34    1  2    2   2   2   2   2   2   2   2   2    2  1.00    ?  200   
4  2  34    1  2    2   2   2   2   2   2   2   2   2    2  0.90   95   28   

     4   7  1.3  
0  3.5   ?    1  
1  4.0   ?    1  
2  4.0  80    1  
3  4.0   ?    1  
4  4.0  75    1

In [21]:
df1=df.replace("?",0)

In [22]:
df1.head()

2  30  2.1  1  2.2 2.3 2.4 2.5 1.1 2.6 2.7 2.8 2.9 2.10   1.2   85   18  \
0  2  50    1  1    2   1   2   2   1   2   2   2   2    2  0.90  135   42   
1  2  78    1  2    2   1   2   2   2   2   2   2   2    2  0.70   96   32   
2  2  31    1  0    1   2   2   2   2   2   2   2   2    2  0.70   46   52   
3  2  34    1  2    2   2   2   2   2   2   2   2   2    2  1.00    0  200   
4  2  34    1  2    2   2   2   2   2   2   2   2   2    2  0.90   95   28   

     4   7  1.3  
0  3.5   0    1  
1  4.0   0    1  
2  4.0  80    1  
3  4.0   0    1  
4  4.0  75    1

In [23]:
df1.columns

Index(['2', '30', '2.1', '1', '2.2', '2.3', '2.4', '2.5', '1.1', '2.6', '2.7',
       '2.8', '2.9', '2.10', '1.2', '85', '18', '4', '7', '1.3'],
      dtype='object')

In [25]:
df1.isnull().sum()

2       0
30      0
2.1     0
1       0
2.2     0
2.3     0
2.4     0
2.5     0
1.1     0
2.6     0
2.7     0
2.8     0
2.9     0
2.10    0
1.2     0
85      0
18      0
4       0
7       0
1.3     0
dtype: int64

In [29]:
df1.describe()

2          30         2.1         2.2         1.3
count  154.000000  154.000000  154.000000  154.000000  154.000000
mean     1.792208   41.272727    1.097403    1.844156    1.454545
std      0.407051   12.574106    0.297473    0.363891    0.499554
min      1.000000    7.000000    1.000000    1.000000    1.000000
25%      2.000000   32.000000    1.000000    2.000000    1.000000
50%      2.000000   39.000000    1.000000    2.000000    1.000000
75%      2.000000   50.000000    1.000000    2.000000    2.000000
max      2.000000   78.000000    2.000000    2.000000    2.000000

In [72]:
X = df1.drop(['1.3'],axis=1)
y = df1['1.3']

#perform training and test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=80)

#Dummy Classifier
from sklearn.dummy import DummyClassifier
clf = DummyClassifier(strategy= 'most_frequent').fit(X_train,y_train)
y_pred = clf.predict(X_test)

#Distribution of y test
print('y actual : \n' +  str(y_test.value_counts()))

#Distribution of y predicted
print('y predicted : \n' + str(pd.Series(y_pred).value_counts()))

y actual : 
1    28
2    11
Name: 1.3, dtype: int64
y predicted : 
2    39
dtype: int64


In [73]:
# Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred)))
print('Precision Score : ' + str(precision_score(y_test,y_pred)))
print('Recall Score : ' + str(recall_score(y_test,y_pred)))
print('F1 Score : ' + str(f1_score(y_test,y_pred)))

#Dummy Classifier Confusion matrix
from sklearn.metrics import confusion_matrix
print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))


Accuracy Score : 0.28205128205128205
Precision Score : 0.0
Recall Score : 0.0
F1 Score : 0.0
Confusion Matrix : 
[[ 0 28]
 [ 0 11]]


In [74]:
#Logistic regression
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression().fit(X_train,y_train)
y_pred = clf.predict(X_test)

# Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print('Accuracy Score : ' +str(accuracy_score(y_test,y_pred)))
print('Precision Score : '+str(precision_score(y_test,y_pred)))
print('Recall Score : ' +str(recall_score(y_test,y_pred)))
print('F1 Score : ' +str(f1_score(y_test,y_pred)))

#Logistic Regression Classifier Confusion matrix
from sklearn.metrics import confusion_matrix
print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))

Accuracy Score : 0.6666666666666666
Precision Score : 0.8
Recall Score : 0.7142857142857143
F1 Score : 0.7547169811320756
Confusion Matrix : 
[[20  8]
 [ 5  6]]


In [75]:
#Grid Search to maximize Recall
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import GridSearchCV
clf = LogisticRegression()
grid_values = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values,scoring = 'recall')
grid_clf_acc.fit(X_train, y_train)

#Predict values based on new parameters
y_pred_acc = grid_clf_acc.predict(X_test)

# New Model Evaluation metrics 
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test,y_pred_acc)))
print('Recall Score : ' + str(recall_score(y_test,y_pred_acc)))
print('F1 Score : ' + str(f1_score(y_test,y_pred_acc)))

#Logistic Regression (Grid Search) Confusion matrix
confusion_matrix(y_test,y_pred_acc)

Accuracy Score : 0.717948717948718
Precision Score : 0.717948717948718
Recall Score : 1.0
F1 Score : 0.835820895522388


array([[28,  0],
       [11,  0]], dtype=int64)

In [ ]:
from sklearn.external import joblib
joblib.dump()